### ISSUE TITLE
Incorrect reward furni for talent track

### ISSUE THREAD

**Issue by Killua99x** [Wulles/Wulez#1]
Hi, i want to report this problem

[LOADING] Incorrect reward furni (ID: 508) for talent track level 0
[LOADING] Incorrect reward furni (ID: 508) for talent track level 1
[LOADING] Incorrect reward furni (ID: 508) for talent track level 2
[LOADING] Incorrect reward furni (ID: 508) for talent track level 3
[LOADING] Incorrect reward furni (ID: 508) for talent track level 4
[LOADING] Incorrect reward furni (ID: 66) for talent track level 4

Thanks!

**Comment by Wulles** [comment]
Thanks for the information, I'll be tidying this up quickly.

**Comment by Wulles** [comment]
Fixed.

https://github.com/Wulles/Wulez/commit/5bd5c0058991280ca25ecb57e3766b172b5ec02b
