### ISSUE TITLE
Furno Forum missing 

### ISSUE THREAD

**Issue by Killua99x** [Wulles/Wulez#3]
Hey Wulles, can you add Forum Terminal furno?
http://prntscr.com/nlwoxk
Thanks in advance!

**Comment by Killua99x** [comment]
http://prntscr.com/nlwto5
http://prntscr.com/nlwwjb
https://i.servimg.com/u/f56/18/41/75/57/immag186.png

**Comment by Wulles** [comment]
Its already. Remember to use the latest sqls from this GitHub.
