### ISSUE TITLE
Hi, on morningstar catalogue missing clothing_on_walk

### ISSUE THREAD

**Issue by Killua99x** [Wulles/Wulez#6]
Hi! Missing clothing_on_walk column
https://prnt.sc/op6iy5
hope you can add this column and add missing furnis with interractions for morningstar
thanks for you job!

**Comment by Wulles** [comment]
[Fixed](https://github.com/Wulles/Wulez/commit/fb71abbaa42c86bb9c7cc429139eb6197beb35cd).
