### ISSUE TITLE
Can't see furni's but the varianles is correct.

### ISSUE THREAD

**Issue by HangoutH** [Wulles/Wulez#7]
Hello i setup your catalog everything is good SQL, SWF's, Variables but I can't see any furnitures. 
![Screenshot_20190811_165644](https://user-images.githubusercontent.com/54001432/62836252-e59d0c80-bc93-11e9-9db3-6bf63109962f.jpg)
![Screenshot_20190811_155809](https://user-images.githubusercontent.com/54001432/62836254-ec2b8400-bc93-11e9-8988-878fcf69e6a4.jpg)
![Screenshot_20190811_155820](https://user-images.githubusercontent.com/54001432/62836255-ecc41a80-bc93-11e9-9aeb-70fa0ccb2247.jpg)
![Uploading Screenshot_20190811_154157.jpg…]()
![Uploading Screenshot_20190811_155745.jpg…]()
![Uploading Screenshot_20190811_155752.jpg…]()
![Uploading Screenshot_20190811_155759.jpg…]()

**Comment by Wulles** [comment]
> Check your links.

**Example:**
Normal wulez use wwwroot, htdocs folder - ads.domain = _http://localhost_ (on variables)
I use the swf in Assets folder = ads.domain = _http://localhost/assets_ (on variables)
