### ISSUE TITLE
Errors and no furni in cata?

### ISSUE THREAD

**Issue by gurvar554** [Wulles/Wulez#8]
Hi I love your catalogue!!

But.. When i installed it i got a lot of errors in my emu..
And in the client there's no furnis in the categories?
Help me.. :/
Please see screenies https://imgur.com/a/DmWI1tW

**Comment by ghost** [comment]
is missing 'subscription_duration' column from some table

**Comment by gurvar554** [comment]
Ok, do you know how i fix it?

**Comment by Wulles** [comment]
@gurvar554 On the screenshot you using the old r2. Use the latest sqls from this Github.

@blackvalves Wulez have this table, on crackables table.

**Comment by gurvar554** [comment]
Yes!! It worked :) Thanks m8!! But.. is there a updated sfw pack coz some furnis r black boxes and some clothes! :)
